Repository milieuinfo/webcomponent-vl-ui-grid, pull requests merged in 2019-12, with the labels that each got.

#47 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#48 Revert naar vl-ui-util v2 wegens afwezigheid van refactoring naar nieuwe opzet testen
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: bugfix

#46 #45 Introductie alignment
  demo/vl-grid.html
  test/vl-grid.test.html
  vl-grid.js
  vl-grid.src.js
Labels: enhancement

#53 #52 Voeg documentatie toe voor vl-layout en vl-region
  vl-grid.src.js
Labels: maintenance

#54 #50 Introduceer vertical alignment
  demo/vl-grid.html
  test/vl-grid.test.html
  vl-grid.src.js
Labels: enhancement

#49 #51 Introduceer extra-small-size en extra-small-max-size voor vl-column
  demo/vl-grid.html
  test/vl-grid.test.html
  vl-grid.src.js
Labels: enhancement
