Repository milieuinfo/webcomponent-vl-ui-grid, pull requests merged in 2020-01, with the labels that each got.

#58 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#59 Test opzet
  .gitignore
  .mocharc.js
  index.js
  package-lock.json
  package.json
  test/e2e/components/vl-grid.js
  test/e2e/grid.test.js
  test/e2e/pages/vl-grid.page.js
  test/unit/vl-grid.test.html
  test/wct.docker.conf.json
Labels: bugfix

#62 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnenDepend op core-branch zonder after
  package.json
Labels: chore

#60 Overbodig NPM release import scripts verwijderd
  package.json
  style.css
  vl-grid.js
Labels: maintenance

#61 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#63 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#64 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
