Repository milieuinfo/webcomponent-vl-ui-grid, pull requests merged in 2020-04, with the labels that each got.

#73 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#78 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#79 Default size en max-size voorzien indien de attributen ontbreken
  demo/vl-grid.html
  src/vl-grid.js
  test/unit/vl-grid.test.html
Labels: enhancement

#80 Introductie medium size attributen en defaults voorzien voor medium, small en extra-small attributen
  demo/vl-grid.html
  dist/vl-grid.js
  dist/vl-grid.min.js
  dist/vl-grid.src.js
  src/vl-grid.js
  test/e2e/components/vl-grid.js
  test/e2e/grid.test.js
  test/unit/vl-grid.test.html
Labels: enhancement
